---
sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
install:
  - if [[ "${TRAVIS_OS_NAME}" = linux ]]; then CMAKE_PLATFORM=Linux; else CMAKE_PLATFORM=Darwin; fi
  - wget "https://cmake.org/files/v3.11/cmake-3.11.0-${CMAKE_PLATFORM}-x86_64.tar.gz"
  - tar -xf "cmake-3.11.0-${CMAKE_PLATFORM}-x86_64.tar.gz"
  - export PATH="${TRAVIS_BUILD_DIR}/cmake-3.11.0-${CMAKE_PLATFORM}-x86_64/bin:${PATH}"
script:
  - mkdir _build
  - cd _build
  - if [[ "${CXX}" = g++ ]]; then OMP_NUM_THREADS=4; fi
  - cmake -DOUTPUT_TIME_AND_POSITIONS=OFF ..
  - ctest -VV -D Experimental .
